### ISSUE TITLE
navigator.clipboard and @media (prefers-color-scheme: dark)

### ISSUE THREAD

**Issue by JohnGu9** [pyloid/pyloid#7]
Recently I tried using this framework. This framework is great. But still get some trouble with it. (ARM base macOS)
1) navigator.clipboard doesn't work. I can't set clipboard directly through JS's navigator.clipboard. But Python's QApplication.clipboard() works fine.
2) @media prefers-color-scheme would not change after app launch. It can't handle the situation that user's computer change system's prefers-color-scheme on fly.

**Comment by aesthetics-of-record** [comment]
Fix it!
You can use it from version 0.16.5

`./venv-pyloid/bin/pip install --upgrade pyloid`

1. It was because QWebEngine was blocking it with permissions.
Currently, the default permission is True.

2. Pyloid now use [data-pyloid-theme].
This attribute allows you to build a more scalable dark mode. It basically follows the theme of the system.
And theme change after app launch. it detect system theme change.

Example
```css
[data-pyloid-theme='light'] {
  --background-color: white;
  --font-color: #333333;
}

[data-pyloid-theme='dark'] {
  --background-color: #333333;
  --font-color: white;
}

body {
  background-color: var(--background-color);
  color: var(--font-color);
}
```

Thanks for the issue!

More issues and features please.
I will solve it as soon as possible :D
